---
# Include OS specific tasks
- include: CentOS.yml
  when: ansible_distribution == "CentOS"
- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
- include: Amazon.yml
  when: ansible_distribution == "Amazon"
