---
- name: gather os specific variables
  #debug: msg="{{ ansible_distribution }}"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"
  tags: vars

- name: print facts
  ansible.builtin.debug:
          var: ansible_distribution_major_version


- name: printmore  facts
  ansible.builtin.debug:
          var: docker_version

  
- name: Run the equivalent of "yum update" as a separate step
  yum:
    name: '*'
    state: latest
    update_cache: true


- name: install python3.6
  package:
    name: "{{item}}" 
    state: present
  loop:
     - python36
     - python3-pip

- name: Ensure Python pip packages are installed
  pip:
    name: "{{ packages }}"
    executable: pip3
  vars:
    packages:
      - docker
      - boto
      - boto3


- name: Add repository into repo.d list
  ansible.builtin.yum_repository:
    name: docker
    description: docker repository
    baseurl: "https://download.docker.com/linux/centos/{{ ansible_distribution_major_version}}/x86_64/stable"
    enabled: true
    gpgcheck: no 

- name: install docker
  yum:
    name:  "docker-ce" 
            #      - docker-ce-cli
            #      - containerd.io
            #     - "docker-ce-{{redhat_docker_version}}"
    state: present
    update_cache: true
  notify:
    - docker restart


      #- name: docker compose 
      #  pip:
      #    name: "{{ packages }}"
      #    executable: pip3
      #  vars:
      #    packages:
      #      - docker-compose
      #  notify:
      #    - docker restart


- name: Enable Docker CE service at startup
  service:
    name: docker
    state: started
    enabled: true


# sudo usermod -aG docker root
- name: Add remote "o/s" user to "docker" group
  user:
    name: "{{item}}"
    groups: "docker"
    append: yes
  with_items: '{{ docker_users }}'
  when: 'docker_users is defined'

# Part 2
- name: pull and start ngnix container
  docker_container:
    image: nginx:stable
    name: nginx
    auto_remove: true
    state: started
    ports:
      - "80:80"

# - include XX.yml
