---
# handlers file for docker
- name: handler for docker restart
  hosts: aws_ec2
  remote_user: root
  become: yes
  handlers:
    - name: Restart docker
      service:
        name: docker
        state: restarted